# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.8"]
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        sudo apt-get install -y libfftw3-bin libfftw3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 python --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 python --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Build PRIISM
      run: python3 setup.py build
      
    - name: Install PRIISM
      run: python3 setup.py install
      
    - name: Test with pytest
      run: |
        pip install pytest
        #pytest
